module.exports = {
	"env": {
		jest: true,
	},
	"plugins": ["jest"],
	"extends": ["plugin:jest/style"],
	"rules": {
		"jest/consistent-test-it": "off",
		"jest/expect-expect": [
			"error",
			{
				"assertFunctionNames": ["expect"],
			},
		],
		"jest/prefer-lowercase-title": ["error", {"ignore": []}],
		"jest/no-alias-methods": "error",
		"jest/no-disabled-tests": "off",
		"jest/valid-title": "error",
		"jest/no-focused-tests": "off",
		"jest/no-hooks": "off",
		"jest/no-identical-title": "error",
		"jest/no-jasmine-globals": "error",
		"jest/no-jest-import": "error",
		"jest/no-mocks-import": "error",
		"jest/no-large-snapshots": "off",
		"jest/no-done-callback": "error",
		"jest/no-test-prefixes": "error",
		"jest/no-test-return-statement": "off",
		"jest/prefer-expect-assertions": "off",
		"jest/prefer-spy-on": "error",
		"jest/prefer-todo": "error",
		"jest/prefer-strict-equal": "warn",
		"jest/prefer-to-contain": "error",
		"jest/prefer-called-with": "error",
		"jest/prefer-to-be": "error",
		"jest/prefer-expect-resolves": "error",
		"jest/prefer-to-have-length": "error",
		"jest/require-tothrow-message": "off",
		"jest/valid-describe-callback": "error",
		"jest/valid-expect-in-promise": "error",
		"jest/valid-expect": "error",
	},
}
